src/Entity/Agence.php
<?php

namespace App\Entity;

use App\Repository\AgenceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: AgenceRepository::class)]
class Agence implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $NomAgence;

    #[ORM\Column(type: 'string', length: 30)]
    private $TelAgence;

    #[ORM\Column(type: 'string', length: 255)]
    private $NumRegistreCom;

    #[ORM\Column(type: 'text', length: 255, nullable: true)]
    private $description;

    #[ORM\Column(type: 'text', length: 255)]
    private $LocationDesc;

    #[ORM\Column(type: 'string', length: 255)]
    private $Longitude;

    #[ORM\Column(type: 'string', length: 255)]
    private $Latitude;

    #[ORM\OneToMany(mappedBy: 'Agence', targetEntity: Offres::class)]
    private $OffresOfAgence;

    #[ORM\Column(type: 'boolean')]
    private $IsVerified;

    #[ORM\Column(type: 'string', length: 255)]
    private $slug;

    public function __construct()
    {
        $this->OffresOfAgence = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getFullName(): ?string
    {
        return $this->getNomAgence();
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';
        $roles[] = 'ROLE_AGENCE';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNomAgence(): ?string
    {
        return $this->NomAgence;
    }

    public function setNomAgence(string $NomAgence): self
    {
        $this->NomAgence = $NomAgence;

        return $this;
    }


    public function getTelAgence(): ?string
    {
        return $this->TelAgence;
    }

    public function setTelAgence(string $TelAgence): self
    {
        $this->TelAgence = $TelAgence;

        return $this;
    }

    public function getNumRegistreCom(): ?string
    {
        return $this->NumRegistreCom;
    }

    public function setNumRegistreCom(string $NumRegistreCom): self
    {
        $this->NumRegistreCom = $NumRegistreCom;

        return $this;
    }

    public function getLocationDesc(): ?string
    {
        return $this->LocationDesc;
    }

    public function setLocationDesc(?string $LocationDesc): self
    {
        $this->LocationDesc = $LocationDesc;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->Longitude;
    }

    public function setLongitude(?string $Longitude): self
    {
        $this->Longitude = $Longitude;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->Latitude;
    }

    public function setLatitude(string $Latitude): self
    {
        $this->Latitude = $Latitude;

        return $this;
    }

    /**
     * @return Collection<int, Offres>
     */
    public function getOffresOfAgence(): Collection
    {
        return $this->OffresOfAgence;
    }

    public function addOffresOfAgence(Offres $offresOfAgence): self
    {
        if (!$this->OffresOfAgence->contains($offresOfAgence)) {
            $this->OffresOfAgence[] = $offresOfAgence;
            $offresOfAgence->setAgence($this);
        }

        return $this;
    }

    public function removeOffresOfAgence(Offres $offresOfAgence): self
    {
        if ($this->OffresOfAgence->removeElement($offresOfAgence)) {
            // set the owning side to null (unless already changed)
            if ($offresOfAgence->getAgence() === $this) {
                $offresOfAgence->setAgence(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->getNomAgence();
    }

    public function isIsVerified(): ?bool
    {
        return $this->IsVerified;
    }

    public function setIsVerified(bool $IsVerified): self
    {
        $this->IsVerified = $IsVerified;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategorieRepository::class)]
class Categorie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $NomCat;

    #[ORM\OneToMany(mappedBy: 'categoriestooffres', targetEntity: Offres::class)]
    private $Offres;

    public function __construct()
    {
        $this->Offres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCat(): ?string
    {
        return $this->NomCat;
    }

    public function setNomCat(string $NomCat): self
    {
        $this->NomCat = $NomCat;

        return $this;
    }

    /**
     * @return Collection<int, Offres>
     */
    public function getOffres(): Collection
    {
        return $this->Offres;
    }

    public function addOffre(Offres $offre): self
    {
        if (!$this->Offres->contains($offre)) {
            $this->Offres[] = $offre;
            $offre->setCategoriestooffres($this);
        }

        return $this;
    }

    public function removeOffre(Offres $offre): self
    {
        if ($this->Offres->removeElement($offre)) {
            // set the owning side to null (unless already changed)
            if ($offre->getCategoriestooffres() === $this) {
                $offre->setCategoriestooffres(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->getNomCat();
    }
}

src/Entity/Offres.php
<?php

namespace App\Entity;

use App\Repository\OffresRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffresRepository::class)]
class Offres
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $NomOffre;

    #[ORM\Column(type: 'float')]
    private $PrixOffres;

    #[ORM\ManyToOne(targetEntity: Categorie::class, inversedBy: 'Offres')]
    #[ORM\JoinColumn(nullable: false)]
    private $categoriestooffres;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Description;

    #[ORM\ManyToMany(targetEntity: Caracteristiques::class, inversedBy: 'offres')]
    private $caracterisiquesofoffres;

    #[ORM\ManyToOne(targetEntity: Agence::class, inversedBy: 'OffresOfAgence')]
    private $Agence;

    #[ORM\Column(type: 'string', length: 255)]
    private $slug;

    public function __construct()
    {
        $this->caracterisiquesofoffres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomOffre(): ?string
    {
        return $this->NomOffre;
    }

    public function setNomOffre(string $NomOffre): self
    {
        $this->NomOffre = $NomOffre;

        return $this;
    }

    public function getPrixOffres(): ?float
    {
        return $this->PrixOffres;
    }

    public function setPrixOffres(float $PrixOffres): self
    {
        $this->PrixOffres = $PrixOffres;

        return $this;
    }

    public function getCategoriestooffres(): ?Categorie
    {
        return $this->categoriestooffres;
    }

    public function setCategoriestooffres(?Categorie $categoriestooffres): self
    {
        $this->categoriestooffres = $categoriestooffres;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection<int, Caracteristiques>
     */
    public function getCaracterisiquesofoffres(): Collection
    {
        return $this->caracterisiquesofoffres;
    }

    public function addCaracterisiquesofoffre(Caracteristiques $caracterisiquesofoffre): self
    {
        if (!$this->caracterisiquesofoffres->contains($caracterisiquesofoffre)) {
            $this->caracterisiquesofoffres[] = $caracterisiquesofoffre;
        }

        return $this;
    }

    public function removeCaracterisiquesofoffre(Caracteristiques $caracterisiquesofoffre): self
    {
        $this->caracterisiquesofoffres->removeElement($caracterisiquesofoffre);

        return $this;
    }

    public function getAgence(): ?Agence
    {
        return $this->Agence;
    }

    public function setAgence(?Agence $Agence): self
    {
        $this->Agence = $Agence;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Controller/OffreController.php
<?php

namespace App\Controller;

use App\Entity\Offres;
use App\Entity\Caracteristiques;
use App\Repository\OffresRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class OffreController extends AbstractController
{
    private $entityManager;
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this -> entityManager= $entityManager;
    }
    

    #[Route('/offre', name: 'offre')]
    public function index(): Response
    {
        $offres = $this -> entityManager->getRepository(Offres::class)->findAll();
        $description = $this -> entityManager->getRepository(Caracteristiques::class)->findAll();
        return $this->render('offre/index.html.twig', [
            'offre' => $offres,
            'description' => $description,
        ]);


    }



    #[Route('/offre/{slug}', name: 'offre_single')]
    public function show($slug): Response
    {
        $offresingle = $this -> entityManager->getRepository(Offres::class)->findOneByslug($slug);
        if(!$offresingle){
            $this->addFlash(
               'notice',
               'Offre Invalid'
            );
            return $this->redirectToRoute('offre');
        }
        return $this->render('offre/show.html.twig', [
            'offresingle'=> $offresingle,
        ]);
    }
}

templates/offre/index.html.twig
{% extends 'base.html.twig' %}
{% block sidebar %}                          
                         {{ render(controller( 'App\\Controller\\OffresCreatedController::findagency')) }}
{% endblock %}
{% block content %}
<div>
    <h2 class="fw-bold fm-poppins mb-0 text-center text-muted h1 mt-4">Nos offres</h2>
    <div class="mb-4 mx-auto row-col-5 py-auto row d-flex justify-content-center">

        <!-- Gradient divider -->
        <div class="col-2 ms-n6">
            <hr>
        </div>
        <i class="fa-solid fa-certificate my-auto col-1 d-flex justify-content-center "></i>
        <div class="col-2 me-n6">
            <hr>
        </div>

    </div>

</div>

<div class="my-1 mx-4 d-flex justify-content-center">
    <span class="fw-bold alert alert-secondary fm-poppins mt-2 text-center px-auto text-muted h8">A votre attention pour
        des raison d'ethique le prix des offres ne sera afficher que lorsque vous procedere a l'achat</span>
</div>

<div class="row mx-4 my-3">
    <div class="col-md-3 mx-auto px-auto">
        <div class="input-group mx-3">
            <h1 class="my-2 h5 fm-poppins fw-bold text-muted">Rechercher l'offre qui vous conviendra le mieux</h1>
            <input type="search" name="" class="form-control" id="">
            <button type="button" class="btn btn-sm btn-danger"> <i class="fas fa-search mx-1"></i></button>
            <h1 class="my-2 h6 fm-poppins fw-bold text-muted mb-1 ms-3">Trier</h1>
            <h1 class="my-2 h6 fm-poppins fw-bold text-muted card p-2 mt-0">Par categorie</h1>
            <div class="form-check form-switch w-100 my-2 ms-2">
                <input class="form-check-input ckeck" type="checkbox" role="switch" id="flexSwitchCheckChecked">
                <label class="form-check-label" for="flexSwitchCheckChecked">Assurance vie</label>
            </div>
            <div class="form-check form-switch w-100 my-2 ms-2">
                <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked">
                <label class="form-check-label" for="flexSwitchCheckChecked">Assurance Maladie</label>
            </div>
            <div class="form-check form-switch w-100 my-2 ms-2">
                <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked">
                <label class="form-check-label" for="flexSwitchCheckChecked">Assurance Vehicule</label>
            </div>
            <div class="form-check form-switch w-100 my-2 ms-2">
                <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked">
                <label class="form-check-label" for="flexSwitchCheckChecked">Assurance pour votre maison</label>
            </div>


            <h1 class="my-2 h6 fm-poppins fw-bold text-muted card p-2 mt-0">Par etablissement</h1>
            <div class="form-check form-switch w-100 my-2 ms-2">
                <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked">
                <label class="form-check-label" for="flexSwitchCheckChecked">Assurance vie</label>
            </div>
            <div class="form-check form-switch w-100 my-2 ms-2">
                <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked">
                <label class="form-check-label" for="flexSwitchCheckChecked">Assurance Maladie</label>
            </div>
            <div class="form-check form-switch w-100 my-2 ms-2">
                <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked">
                <label class="form-check-label" for="flexSwitchCheckChecked">Assurance Vehicule</label>
            </div>
            <div class="form-check form-switch w-100 my-2 ms-2">
                <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked">
                <label class="form-check-label" for="flexSwitchCheckChecked">Assurance pour votre maison</label>
            </div>


        </div>
    </div>

    <div class="col-md-9 row mx-auto px-auto d-flex justify-content-start">
        <div class="d-block d-md-none my-2 fm-popins text-center h7 p-4 bg-secondary bg-opacity-25">Resultats des
            recherches </div>
            {% for offres in offre %}
            <div class="col-md-5 col-lg-4">

            <div class="card m-2">
                <div class="card-header bg-dark text-white fm-poppins text-truncate">
                    <img src="{{asset('smart-labs-assets/img/IMG_0727.jpeg')}}" height="30" width="30" alt=""
                        class="rounded-circle">
                     
                                {{offres.Agence.NomAgence}} 
             
                  
                </div>
                <span class="text-black badge mt-2 mb-0">{{offres.categoriestooffres.nomCat}}</span>

                <div class="card-body  text-white">
                    <h5 class="card-body bg-danger rounded-3 text-center fm-poppins fw-bold small mb-0">Assurance combo
                         {{offres.NomOffre}}</h5>
                    <div class=" bg-secondary small mt-0 rounded-bottom bg-opacity-25  small py-1 px-2 w-80 mx-auto">
                      {#  <a id="trianglesecondary" class="position-absolute top-75 start-50 translate-middle" style="margin-top:-10px;"></a>#}
                        <span class=" small text-center fm-poppins small text-black">{{offres.Description}}</span>
                    </div>
                    <div class="text-black ">
                   {#
                {% for Description in offres.caracterisiquesofoffres %}
                 <span><i class="fas fa-circle" style="font-size:7px;"></i>
                    {{Description.Description}} 
                    <span class="badge bg-danger">{{Description.TauxReduc}} %</span>
                    </span>
                    </br>
                {% endfor %}
                #}
            </div>
                </div>
                <div class=" mt-0 mb-2 mx-2">
                    <a href="{{path('offre_single' , { 'slug': offres.slug } )}}" class="btn btn-dark text-nowrap w-50 btn-sm ">Souscrire</a>
                </div>
            </div>
        </div>
            {% endfor %}





    </div>
</div>

<div style="margin-bottom:15em;"></div>
{% endblock %}

templates/offre/show.html.twig
{% extends "base.html.twig" %}
{% block sidebar %}                          
                         {{ render(controller( 'App\\Controller\\OffresCreatedController::findagency')) }}
{% endblock %}
{% block content %}
<div class="d-flex justify-content-center text-wrap">
    <a class="fw-bold fm-poppins mb-0  h5 mt-4 link-secondary text-decoration-none" href="{{path('offre')}}">Offres</a><span class="fw-bold fm-poppins mb-0 text-muted h5 mt-4 text-decoration-none lh-sm opacity-50"> <i class="fas fa-angle-right mx-2 my-auto"></i> </span><a class="fw-bold fm-poppins mb-0 link-secondary h5 mt-4 text-decoration-none">{{offresingle.NomOffre}}</a>
   

</div>
  	<div class="container my-5">
		<div class="card">
			<div class="container-fliud">
				<div class="wrapper row">
					<div class="  col-md-6 text-center my-auto">
						
						<div class="bg-secondary bg-opacity-25 m-5 p-5 d-flex justify-content-center">
						  <div class="mx-4" id=""><span class="fm-poppins m-auto text-wrap text-center h-1 fw-bold text-muted">{{offresingle.NomOffre}}</span></div>

						</div>
					<button class="btn-md btn btn-danger mx-auto">Souscrire {{offresingle.PrixOffres /100}} XOF</button>
						
					</div>
					<div class="details col-md-6 p-4">
						<h3 class="ms-sm-3 ms-md-0">{{offresingle.NomOffre}}</h3>
						<div class="rating">

							<span class="review-no">41 personnes ont deja souscrit a cette offres</span>
						</div>
                        <p class="small fw-bold mt-2">Description :</p>
						<p class="mt-2">
							{{offresingle.Description}}
						</p>
						<h4 class="price">Prix : <span>{{(offresingle.PrixOffres /100)|number_format(0, ',', '.')}} XOF</span></h4>
						<p class="vote">Proposer par :<strong> {{offresingle.agence.NomAgence}}</strong>
						{% if offresingle.agence.isVerified == true %}
							<span class="text-success"><i class="fas fa-certificate mx-1"></i> Vérifier</span>
						
								{% else %}
							<span class="text-warning"><i class="fas fa-warning mx-1"></i>Non Vérifier</span>
						{% endif %}
						</p>
					
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
	 {% for Description in offresingle.caracterisiquesofoffres %}
                 <span><i class="fas fa-circle" style="font-size:7px;"></i>
                    {{Description.Description}} 
                    <span class="badge bg-danger">{{Description.TauxReduc}} %</span>
                    </span>
                    </br>
                {% endfor %}
				</div>
    <div style="margin-bottom:15rem;"></div>
{% endblock %}